import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

import { Rochester } from "next/font/google"

const rochester = Rochester({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-rochester",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${rochester.variable} flex relative flex-col overflow-y-scroll`}
      >
        {children}
      </body>
    </html>
  )
}
